site_name: Swagger2Markup DEMO
repo_url: https://github.com/RobWin/spring-swagger2markup-demo
theme: readthedocs
markdown_extensions: [admonition]
pages:
- ['index.md', 'Index']
- ['generated/swagger.md', 'Demo API', 'Demo API']
